version: "3.3"

services:
  app:
    container_name: jet-terabox
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "50:50"
      - "8000:8000"
